lightfm/lightfm.py
lightfm/lightfm_fast.c
lightfm/lightfm_fast.pyx
setup.py
tests/test_movielens.py

Add gradient clipping for WARP training for numerical stability.

Add parallel training for WARP and BPR losses.

---

changelog.md
lightfm/lightfm.py
setup.py
tests/test_api.py

Addresses https://github.com/lyst/lightfm/issues/21

Automatically convert input matrices to correct datatype.

---

README.md

Add Kaggle example link

---

examples/crossvalidated/data.py

Quick fix to use the right import for HTMLParser.

FIX python 3 support in cross-validated example

---

examples/crossvalidated/data.py

Fixes https://github.com/lyst/lightfm/issues/54

Fix subclassing of Python 3.5 HTMLParser.

---

lightfm/lightfm.py
tests/test_api.py
tests/test_movielens.py

This makes it harder to shoot yourself in the foot by misaligning the weights and the interactions.

Change sample_weight API to accept COO matrices.

---

doc/examples/warp_loss.rst
doc/home.rst

Valuable contribution right here :)

Fix documentation typos.

---

changelog.md
dev-requirements.txt
setup.py

Fixes https://github.com/lyst/lightfm/issues/87

Update scipy dependency version.

---

setup.py

Solves https://github.com/lyst/lightfm/issues/89

Use text mode for cythonize.

---

CONTRIBUTORS
changelog.md

Add contributors file and update changelog.

---

Dockerfile

Added an 'apt-get' line in the Dockerfile so that scipy installs successfully
issues: fixes #101

Fixed issue #101 install blas, required for scipy

---

examples/movielens/example.ipynb

FIX missing imports in example

---

README.md

Really nothing, just a missing dot.

Missing dot in README.md

---

Dockerfile
doc/home.rst
docker-compose.yml

The gist of the problem is that the current directory was mounted by default, and it didn't have the compiled extensions.
https://github.com/lyst/lightfm/issues/211

Update Docker instructions.

---

lightfm/datasets/movielens.py

the dimensions specified in the docstring should be `n_items` instead of `n_users`

fix fetch_movielens docstring

---

lightfm/lightfm.py

Got distracted by other stuff yesterday ...

additional regularization docstrings

---

lightfm/data.py

Hi!
Thanks for the awesome work on this project. The data builder class popped up just in time for me right as when I was about to write this for myself, and is a great, much awaited addition!
I had been using the variant from the PR before and just updated the lib, but saw that there was a character missing in the exception. I usually don't do these type of contributions but thought I'd help out. 
I wanted to go all in and add some more stuff in the exception, because the feature's name is just a character in my case and doesn't explain a lot, but I thought I'd drop this PR and hear what you guys think of it. It would be great if I knew what feature this was concerning, index and itemID so I can look over what's going on with my data.
Also, my editor did some cleaning in the formatting. …

Corrected typo for exception. Cleaned formatting.

---

lightfm/evaluation.py
lightfm/lightfm.py

This will raise an error when num_threads < 1 as requested in #396

Raise exception when num_threads < 1

---

doc/index.rst
doc/quickstart.rst
examples/quickstart/quickstart.ipynb
lightfm/cross_validation.py
lightfm/data.py
lightfm/evaluation.py
lightfm/lightfm.py

This fixes a few typos and clarifies some things in the docs / error messages that tripped me up previously.

Tweak docs and fix typos.

---

tests/test_movielens.py

Fix simple typo: shoul -> should

---

examples/dataset/readme.rst

Building the interactions matrix readme.rst - typo fix

Typo fix - Build dataset section.

---

setup.py

setup: Allow CFLAGS to set arch when a native build isn't desirable

---

changelog.md
lightfm/__init__.py
setup.py

Update changelong.
Add long description to setup.py.

Bump version to v1.16.

---

.github/workflows/test.yaml

Run GitHub Actions Tests added in #679 on Pull Request builds

Run Tests on Pull Request builds
