lyst/lightfm

changelog.md, setup.py
when homebrew installed gcc it created these links:
```
$ ls -alh /usr/local/bin/gcc*
lrwxr-xr-x  1 jongwook  admin    29B Sep 15 00:55 /usr/local/bin/gcc-5 -> ../Cellar/gcc/5.2.0/bin/gcc-5
lrwxr-xr-x  1 jongwook  admin    32B Sep 15 00:55 /usr/local/bin/gcc-ar-5 -> ../Cellar/gcc/5.2.0/bin/gcc-ar-5
lrwxr-xr-x  1 jongwook  admin    32B Sep 15 00:55 /usr/local/bin/gcc-nm-5 -> ../Cellar/gcc/5.2.0/bin/gcc-nm-5
lrwxr-xr-x  1 jongwook  admin    36B Sep 15 00:55 /usr/local/bin/gcc-ranlib-5 -> ../Cellar/gcc/5.2.0/bin/gcc-ranlib-5
```
which setup.py didn't pick up. 
this commit is on top of your pull request #26 and should be merged after.
=> Support homebrew gcc-5

lightfm/datasets/stackexchange.py
fix the warning:
```sh
lightfm/datasets/stackexchange.py:101: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
* (1.0 - test_set_fraction)]
```
=> fix numpy VisibleDeprecationWarning

changelog.md, lightfm/lightfm.py, tests/test_api.py
Addresses https://github.com/lyst/lightfm/issues/117
=> Fix segfault on duplicate entries in COO matrices.

lightfm/evaluation.py
For the case where k = 1, setting all the rank=0 values to '1' is immediately overwritten. By saving-off the indices first, the ranks data is updated without this issue.
=> Update evaluation.py - include case where k = 1

CONTRIBUTORS, lightfm/evaluation.py, lightfm/lightfm.py, setup.py
Hi,
I reformatted the docstrings / some long code lines, so it follows the Python style standard (<79).
Now I can split my editor and still read (almost) everything without horizontal scrolling, also PyCharm doesn't cry about it anymore. I kept some long lines unchanged, because they were more readable that way.
Also fixed some typos and added utf-8 comments.
Btw I enjoy using your library, keep up the good work! Although I've got some concerns about the validity of the tests, because at first glance it doesn't seem to separate the features, so the tests are only valid when checked in an interaction-only scenario. I'd be glad to work out some solution / open an issue if that's the case. Of course: correct me if I'm wrong.
Best regards,
Mice Pápai
=> Reformat where it's sensible (PEP8), Add coding=utf-8 comments

setup.py
Fix error:
```
dh clean --with python2,python3 --buildsystem=pybuild
dh_testdir -O--buildsystem=pybuild
dh_auto_clean -O--buildsystem=pybuild
I: pybuild base:170: python2.7 setup.py clean 
running clean
error: error in /home/atikunov/build/trusty/python-lightfm/deb_dist/lightfm-1.13/.pybuild/pythonX.Y_2.7/.pydistutils.cfg: command 'Clean' has no such option 'all'
E: pybuild pybuild:256: clean: plugin distutils failed with: exit code=1: python2.7 setup.py clean
```
=> build with pybuild

changelog.md, lightfm/datasets/movielens.py
Handles https://github.com/lyst/lightfm/issues/134 and https://stackoverflow.com/questions/46138406/build-error-if-you-try-to-use-lightfm-data-sets.
=> Make Movielens code robust to corrupted downloads.

changelog.md, lightfm/lightfm.py, tests/test_api.py
Apparently it's possible to pass in inputs so _spectacularly_ wrong as
to make int32s overflow and segfault the indexing code.
=> Check that the inputs passed do not overflow.

lightfm/lightfm.py, tests/test_api.py
Doing so can change the order of the
entries (https://github.com/lyst/lightfm/issues/272) for details.
=> Don't use astype on the sparse weights matrix.

lightfm/evaluation.py, lightfm/lightfm.py, tests/test_api.py, tests/test_evaluation.py
As discussed in[ this issue.](https://github.com/lyst/lightfm/issues/287)
=> Adding an optional check for intersections between test and train matrices in predict_rank().

dev-requirements.txt, lightfm/data.py
Fix indentation in Dataset docs. Included sphinx and sphinx_rtd_theme in requirements so that documents can build without issues.
Addresses issue: https://github.com/lyst/lightfm/issues/327
=> Fix indentation to correct Sphinx formatting.

lightfm/lightfm.py
If `tqdm` is installed, `tqdm.trange()` will be used to display a progress bar. Otherwise, this conserves the prior behaviour.
=> Add tqdm support

lightfm/datasets/stackexchange.py
Sum duplicate coordinates in the serialized stackexchange dataset to prevent duplicate interactions in test and train. Fixes https://github.com/lyst/lightfm/issues/421
=> Sum duplicates in stackexchange serialized dataset

setup.py
This PR fixes an issue caused by requiring `scikit-learn` only for the tests.
`scikit-learn` is indeed used in the tests, but it is also required in the `lightfm.data` module. However, `scikit-learn` is a requirement only for tests and not for `lightfm`.
For example, end users, who install the package through PyPI, will face a `ModuleNotFoundError` when trying to import `lightfm.data`.
```python
>>> from lightfm.data import Dataset
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/davide.sarra/.pyenv/versions/lfm/lib/python3.6/site-packages/lightfm/data.py", line 7, in <module>
import sklearn.preprocessing
ModuleNotFoundError: No module named 'sklearn'
```
=> Require scikit-learn dependency not just for tests

lightfm/data.py
Fix the return values of the Dataset.mapping() function in documentation
=> Doc-fix: correct return value of mapping

lightfm/lightfm.py, tests/test_api.py
Closes #532 .
This is a small PR that just checks if the input to `LightFM.predict()` is in fact either `np.ndarray` or `int` type. It also includes a line in `test_predict()` to make sure this doesn't break later. The docs weren't changed because they already implied that the only acceptable input was `np.ndarray` or `int`.
Let me know if you'd rather not use an `AssertionError` there. I used it because a couple lines later there's another `assert` statement, and I figured you'd want some consistency.
=> Predict with ndarrays/int only

README.md
Hi,
I pulled your repo to have a poke around and noticed I was unable to run the test suite following the instructions in the README (since, from what I can see, `setup.py test` expects a `unittest` test suite). After a quick look in the CI config I updated the command in the README. Also following the CI config I added instructions to setup a virtualenv and install test dependencies.
=> Update readme development instructions

doc/examples/hybrid_crossvalidated.rst
Hi!
I've tried to complete this tutorial and faced some issues due to the discrepancy between lightfm latest version and the one used in the tutorial.
The issue was that checking test AUC score without `check_intersections=False` raises an Exception due to intersected samples.
=> Update Hybrid Recommender Tutorial

.gitignore, .idea/lightfm.iml, lightfm/lightfm.py, tests/test_api.py, tests/test_movielens.py
Hey!
I've submitted this PR primarily to resolve a minor issue that (I feel) violates 'the principle of least surprise'.
The `predict` method accepts `user_ids` and `item_ids` parameters. For `item_ids`, a couple of coercion steps are used to massage the input into a `ndarray` of type `np.int32`. This includes casting `item_ids` of type `list` and `tuple` to `ndarray` as needed. In contrast, if `user_ids` are provided as a type other than `ndarray`, a `TypeError` is raised. In other words, if I call `lfm.predict(user_ids=[0, 1, 2, 3], item_ids=[7, 6, 5, 4])` would currently throw a `TypeError` for the type of the `user_ids` parameter, but not the `item_ids` parameter. This PR ensures parity between the two.
I've also switched out the assertion used to check `user_ids` and `item_ids` in …
=> Update to ensure user-item type handling parity in predict method

setup.py
In response to https://github.com/lyst/lightfm/issues/622.
I skip the `march=native` for MacOs to avoid problems with apple silicone. This might result in a performance loss but we go the same route when building for conda-forge and in my personal experience, there wasn't a noticeable performance hit. I decided against specifying `-mcpu=apple-m1` because I am not sure how stable/robust the flag is and whether requirements towards the compiler toolchain would be too restrictive.
I took some inspiration from this thread https://github.com/irmen/pyminiaudio/issues/30
Other:
- I removed the condition on "anaconda". Afaik, this was a problem with macOS and should be covered with the above.
=> Skip march=native for apple

.circleci/config.yml, README.md, doc/conf.py, examples/dataset/download.py, examples/movielens/data.py, lightfm/datasets/_common.py, lint-requirements.txt, tests/test_data.py
This upgrades to the new circleci convenience images. The formerly used images are deprecated. See: https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034
A few other changes stacked up while fixing the CI/CD Pipeline: 
- Removed python 3.6 from test matrix (reached end of life)
- Added python 3.9 to test matrix
- Fixed the black version to have deterministic re-formatting
- Re-format repo with new black version (all in one commit: [80195429dbe374cd57dac11a762a92c63e1224de](https://github.com/lyst/lightfm/pull/629/commits/22e1c3b91006e9c917b9d6f627dc33648e651304))
- I initially tried to add python 3.10 but there were a few problems with the setup.py
=> Upgrade deprecated circleci images

docker-compose.yml
Small upgrade from the deprecated version 1 composes file. The only change is that all services must be declared under the `services` key (https://docs.docker.com/compose/compose-file/compose-versioning/#version-2)
=> Upgrade from depreacted version 1 compose

.gitignore, doc/conf.py, docs-requirements.txt
Hi @maciejkula,
I changed a few lines in doc/conf.py that were necessary to build the docs with a newer sphinx version. I also added a `docs-requirements.txt`. 
In my opinion, having three requirements files is quite ugly and development usually requires all three of them. However, without using sth. like pryproject.toml I don't have a better idea for organizing this (also considering minimal installation for CI/CD). 
Also: 
- Added .devcontainer to the gitignore. This allows me and others to use the VSCode devcontainer feature to develop for linux/amd64 on an apple m1.
=> Update dependencies for creating Docs

doc/home.rst
There is a small typo in doc/home.rst.
Should read `section` rather than `secion`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, secion -> section
